//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteSmartHint.Libraries.Lang {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagem() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TesteSmartHint.Libraries.Lang.Mensagem", typeof(Mensagem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este e-mail já está cadastrado..
        /// </summary>
        public static string MSG__EMAIL {
            get {
                return ResourceManager.GetString("MSG__EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} é obrigatório!.
        /// </summary>
        public static string MSG_E001 {
            get {
                return ResourceManager.GetString("MSG_E001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ter no mínimo {1} caracteres!.
        /// </summary>
        public static string MSG_E002 {
            get {
                return ResourceManager.GetString("MSG_E002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ter no máxiimo {1} caracteres!.
        /// </summary>
        public static string MSG_E003 {
            get {
                return ResourceManager.GetString("MSG_E003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} não é válido!.
        /// </summary>
        public static string MSG_E004 {
            get {
                return ResourceManager.GetString("MSG_E004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor do campo {0} não confere com o valor do campo {1}!.
        /// </summary>
        public static string MSG_E005 {
            get {
                return ResourceManager.GetString("MSG_E005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor do campo (0) não se encontra entre (1) e (2).
        /// </summary>
        public static string MSG_E006 {
            get {
                return ResourceManager.GetString("MSG_E006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário Expirado contate o administrador do Sistema..
        /// </summary>
        public static string MSG_E007 {
            get {
                return ResourceManager.GetString("MSG_E007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &quot;Cliente não encontrado.&quot;.
        /// </summary>
        public static string MSG_E008 {
            get {
                return ResourceManager.GetString("MSG_E008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve ser diferente da anterior!.
        /// </summary>
        public static string MSG_E009 {
            get {
                return ResourceManager.GetString("MSG_E009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuario não encontrado, verifique o e-mail e senha digitado!.
        /// </summary>
        public static string MSG_E010 {
            get {
                return ResourceManager.GetString("MSG_E010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário Bloqueado contate o administrador do Sistema..
        /// </summary>
        public static string MSG_E011 {
            get {
                return ResourceManager.GetString("MSG_E011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum cliente selecionado para exclusão..
        /// </summary>
        public static string MSG_E012 {
            get {
                return ResourceManager.GetString("MSG_E012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum Cliente Selecionado para Bloquear..
        /// </summary>
        public static string MSG_E013 {
            get {
                return ResourceManager.GetString("MSG_E013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este CPF/CNPJ já está cadastrado..
        /// </summary>
        public static string MSG_ECPF_CNPJ {
            get {
                return ResourceManager.GetString("MSG_ECPF_CNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Está inscrição estadual já está cadastrada..
        /// </summary>
        public static string MSG_EINSC {
            get {
                return ResourceManager.GetString("MSG_EINSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro salvo com sucesso!.
        /// </summary>
        public static string MSG_S001 {
            get {
                return ResourceManager.GetString("MSG_S001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro excluído com sucesso!.
        /// </summary>
        public static string MSG_S002 {
            get {
                return ResourceManager.GetString("MSG_S002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha alterada com sucesso!.
        /// </summary>
        public static string MSG_S003 {
            get {
                return ResourceManager.GetString("MSG_S003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro desativado com sucesso!.
        /// </summary>
        public static string MSG_S004 {
            get {
                return ResourceManager.GetString("MSG_S004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro ativado com sucesso!.
        /// </summary>
        public static string MSG_S005 {
            get {
                return ResourceManager.GetString("MSG_S005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro realizado com sucesso!.
        /// </summary>
        public static string MSG_S006 {
            get {
                return ResourceManager.GetString("MSG_S006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atualização realizada com sucesso!.
        /// </summary>
        public static string MSG_S007 {
            get {
                return ResourceManager.GetString("MSG_S007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuarios Bloqueados com Sucesso!.
        /// </summary>
        public static string MSG_S010 {
            get {
                return ResourceManager.GetString("MSG_S010", resourceCulture);
            }
        }
    }
}
